const global_profile = {
  name: "TODO科技",
  enName: "TODO Software Solutions",
  fullName: "TODO科技有限公司",
  localName: "土杜科技有限公司",
  web: "www.todosln.com",
  email: "service@todosln.com",
  phone: "--",
  mobile: "0915-257-003",
  address: "新北市林口區文化二路一段266號B1-8",
  bank: "玉山銀行 (808) 林口分行",
  bankTitle: "土杜科技有限公司",
  bankNum: "--",
  tax: "90018797",
};
